[package]
name = "ros_studio_daemon"
version = "0.1.0"
edition.workspace = true
publish.workspace = true
license = "GPL-3.0-or-later"

[lints]
workspace = true

[lib]
path = "src/ros_studio_daemon.rs"
doctest = false

[[bin]]
name = "ros-studio-daemon"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
futures-lite.workspace = true
rclrs = { version = "0.7", optional = true }
ros_studio_model.workspace = true
ros_studio_protocol.workspace = true
serde.workspace = true
serde_json.workspace = true
smol.workspace = true

[target.'cfg(unix)'.dependencies]
nix = { workspace = true, features = ["signal"] }

[features]
default = []
ros-runtime = ["dep:rclrs"]

[dev-dependencies]
tempfile.workspace = true
